version: '3.8'

services:
  rag-bot:
    build: .
    container_name: rag-telegram-bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GIGACHAT_TOKEN=${GIGACHAT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
